#pragma once

#include "driver/gpio.h"
#include "driver/i2c_types.h"
#include "esp_adc/adc_oneshot.h"

#define COLLAR_SHUTTLE_I2C_PORT   I2C_NUM_0
#define COLLAR_SHUTTLE_I2C_SCL    GPIO_NUM_3
#define COLLAR_SHUTTLE_I2C_SDA    GPIO_NUM_2
#define COLLAR_I2C_SCL_GPIO       COLLAR_SHUTTLE_I2C_SCL
#define COLLAR_I2C_SDA_GPIO       COLLAR_SHUTTLE_I2C_SDA
#define COLLAR_BM_G2_GPIO         GPIO_NUM_0
#define COLLAR_BM_G1_GPIO         GPIO_NUM_28
#define COLLAR_BM_CS_GPIO         GPIO_NUM_10
#define COLLAR_BM_SDO_GPIO        GPIO_NUM_9

#define COLLAR_BMI_INT1_GPIO      COLLAR_BM_G2_GPIO
#define COLLAR_BMI_INT2_GPIO      COLLAR_BM_G1_GPIO
#define COLLAR_BMI_CS_GPIO        COLLAR_BM_CS_GPIO
#define COLLAR_BMI_SDO_GPIO       COLLAR_BM_SDO_GPIO

#define COLLAR_MOTOR_GPIO         GPIO_NUM_4
#define COLLAR_EXT_GPIO5          GPIO_NUM_5

#define COLLAR_WS2812_GPIO        GPIO_NUM_26
#define COLLAR_LED_DATA_GPIO      COLLAR_WS2812_GPIO

#define COLLAR_SPEAKER_PA_GPIO    GPIO_NUM_23
#define COLLAR_SPEAKER_PDM_P_GPIO GPIO_NUM_24
#define COLLAR_SPEAKER_PDM_N_GPIO GPIO_NUM_25

#define COLLAR_BUZZER_GPIO        GPIO_NUM_22

#define COLLAR_BAT_ADC_CHANNEL    ADC_CHANNEL_5

#define COLLAR_LCD_PWR_GPIO       GPIO_NUM_5
